CREATE TABLE "ATG_TIMESHEET"(
 "USER_ID" CHAR(8),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "BEG_WEEK" DATE,
 "SUN_HRS" DOUBLE,
 "MON_HRS" DOUBLE,
 "TUES_HRS" DOUBLE,
 "WED_HRS" DOUBLE,
 "THUR_HRS" DOUBLE,
 "FRI_HRS" DOUBLE,
 "SAT_HRS" DOUBLE,
 "UPDATED" BIT NOT NULL );
